name: HuskChatTestEvents
main: dev.truewinter.huskchattestevents.bukkit.HuskChatTestEvents
version: ${project.version}
author: TrueWinter
commands:
  impersonate:
    description: Impersonates another player
    usage: /impersonate <player> <message>
depend:
  - HuskChat